# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workAndemployment', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('description', models.TextField(default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
