# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170404_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pictures/Dp.png', upload_to='profile_pictures'),
        ),
    ]
