# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_socratessearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socratessearch',
            old_name='search_date',
            new_name='searchdate',
        ),
    ]
