# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170422_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='newspapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='following',
            name='newspapers',
            field=models.ManyToManyField(to='account.newspapers'),
        ),
    ]
