# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170525_0254'),
        ('account', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='post',
            field=models.ManyToManyField(to='home.Post'),
        ),
    ]
