# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_following_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('published', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(to='home.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
