# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='compare',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
