# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170731_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
