# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('post', models.IntegerField()),
                ('replyto', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Anonymous', max_length=50)),
                ('author', models.CharField(default='Anonymous', max_length=25)),
                ('headline', models.TextField(default='', max_length=1000)),
                ('story', models.TextField(default='', max_length=10000)),
                ('image', models.ImageField(blank=True, default='profile_pictures/Dp.png', upload_to=b'')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pageurl', models.URLField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('suggestions', models.IntegerField(default=0)),
                ('totalcomments', models.IntegerField(default=0)),
                ('comment', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='user',
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
