# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170425_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pageurl',
            field=models.URLField(blank=True, help_text='The URL to newspage', max_length=500, verbose_name='Pagelink'),
        ),
    ]
