# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170512_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
