# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_visits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('headline', 'author')]),
        ),
    ]
