# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20170528_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(to='home.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='The URL to the image page', max_length=1000, verbose_name='Photo Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pageurl',
            field=models.URLField(blank=True, help_text='The URL to newspage', max_length=1000, verbose_name='Pagelink'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='Anonymous', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replyto',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user', 'text')]),
        ),
    ]
