# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20170530_2226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user', 'text', 'created_on')]),
        ),
    ]
